<div class="jumbotron">
    <div class="container justify-content">
        <h3>Kalan Çeviri Hakkınız: <?php echo 3 - $heart; ?></h3>

        <h3> Kullanım hakkınız dolmuştur.</h3>
        <a class="btn btn-danger" href="<?php echo $this->basePath("application/unset");?>" >Kullanıcı Değiştir</a>
        <a class="btn btn-primary" href="<?php echo $this->url('home');?>" >Geri Dön</a>

    </div>
</div>